package eu.thelastdodo.tarock20.entity.enums

enum class CardType(
    val cardColor: CardColor,
    val trickValue: Int,
    val scoreType: CardScoreType,
) {
    PikGlatze(CardColor.Pik, 0, CardScoreType.Glatze),
    PikBube(CardColor.Pik, 1, CardScoreType.Bube),
    PikReiter(CardColor.Pik, 2, CardScoreType.Reiter),
    PikDame(CardColor.Pik, 3, CardScoreType.Dame),
    PikKoenig(CardColor.Pik, 4, CardScoreType.Koenig),

    KaroGlatze(CardColor.Karo, 0, CardScoreType.Glatze),
    KaroBube(CardColor.Karo, 1, CardScoreType.Bube),
    KaroReiter(CardColor.Karo, 2, CardScoreType.Reiter),
    KaroDame(CardColor.Karo, 3, CardScoreType.Dame),
    KaroKoenig(CardColor.Karo, 4, CardScoreType.Koenig),

    KreuzGlatze(CardColor.Kreuz, 0, CardScoreType.Glatze),
    KreuzBube(CardColor.Kreuz, 1, CardScoreType.Bube),
    KreuzReiter(CardColor.Kreuz, 2, CardScoreType.Reiter),
    KreuzDame(CardColor.Kreuz, 3, CardScoreType.Dame),
    KreuzKoenig(CardColor.Kreuz, 4, CardScoreType.Koenig),

    HerzGlatze(CardColor.Herz, 0, CardScoreType.Glatze),
    HerzBube(CardColor.Herz, 1, CardScoreType.Bube),
    HerzReiter(CardColor.Herz, 2, CardScoreType.Reiter),
    HerzDame(CardColor.Herz, 3, CardScoreType.Dame),
    HerzKoenig(CardColor.Herz, 4, CardScoreType.Koenig),

    Tarock1(CardColor.Tarock, 1, CardScoreType.Tarock5),
    Tarock2(CardColor.Tarock, 2, CardScoreType.Tarock1),
    Tarock3(CardColor.Tarock, 3, CardScoreType.Tarock1),
    Tarock4(CardColor.Tarock, 4, CardScoreType.Tarock1),
    Tarock5(CardColor.Tarock, 5, CardScoreType.Tarock1),
    Tarock6(CardColor.Tarock, 6, CardScoreType.Tarock1),
    Tarock7(CardColor.Tarock, 7, CardScoreType.Tarock1),
    Tarock8(CardColor.Tarock, 8, CardScoreType.Tarock1),
    Tarock9(CardColor.Tarock, 9, CardScoreType.Tarock1),
    Tarock10(CardColor.Tarock, 10, CardScoreType.Tarock1),
    Tarock11(CardColor.Tarock, 11, CardScoreType.Tarock1),
    Tarock12(CardColor.Tarock, 12, CardScoreType.Tarock1),
    Tarock13(CardColor.Tarock, 13, CardScoreType.Tarock1),
    Tarock14(CardColor.Tarock, 14, CardScoreType.Tarock1),
    Tarock15(CardColor.Tarock, 15, CardScoreType.Tarock1),
    Tarock16(CardColor.Tarock, 16, CardScoreType.Tarock1),
    Tarock17(CardColor.Tarock, 17, CardScoreType.Tarock1),
    Tarock18(CardColor.Tarock, 18, CardScoreType.Tarock1),
    Tarock19(CardColor.Tarock, 19, CardScoreType.Tarock1),
    Tarock20(CardColor.Tarock, 20, CardScoreType.Tarock1),
    Tarock21(CardColor.Tarock, 21, CardScoreType.Tarock5),
    Gstiess(CardColor.Tarock, 22, CardScoreType.Tarock5),
}